<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OFF</name>
   <tag></tag>
   <elementGuidId>05d9dafd-d495-4194-8268-7a61454d3bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LocationSettingsForm_public_charger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LocationSettingsForm_public_charger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eadaab5d-4b2d-49e3-96eb-23572f041f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LocationSettingsForm_public_charger</value>
      <webElementGuid>5777a5c3-9a1b-44a1-b40c-d879bf27b46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f36df535-e6c1-4a16-b156-6898de11cb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>4da3a5af-7847-4eb0-a1f0-cfd69a2621fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1c60245-b6d8-425d-96e9-2b135d1124cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-switch</value>
      <webElementGuid>0de51452-b333-4aaf-be4b-4b53fa05f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>09d42dac-e1ba-4cf5-897f-1c8dd6fcf013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationSettingsForm_public_charger&quot;)</value>
      <webElementGuid>2c2e84e5-57b8-4de9-89ea-f8114c2a3316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LocationSettingsForm_public_charger']</value>
      <webElementGuid>f5870e4b-6cc4-43e2-8de5-ead6ea52bd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LocationSettingsForm']/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>0b60ce04-814f-4172-8b9e-66c6046d69f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC CHARGER'])[1]/following::button[1]</value>
      <webElementGuid>9c498e84-84a3-4f75-817c-8f06918e5376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSTRUCTIONS'])[1]/following::button[1]</value>
      <webElementGuid>6afe0811-628e-4129-af13-ecbd08de11b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC VISIBILITY'])[1]/preceding::button[1]</value>
      <webElementGuid>694ce166-0ee9-44b0-8f3a-905f128addff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>68f7904b-2707-4eac-91ff-cf97fdb80b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'LocationSettingsForm_public_charger' and @type = 'button' and (text() = 'OFF' or . = 'OFF')]</value>
      <webElementGuid>948bd7ed-c48e-4300-abf6-3c70cc7235e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
