<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Total energy_ant-btn ant-btn-default_38eccf</name>
   <tag></tag>
   <elementGuidId>08745c74-aa16-4417-9e06-f3a8a0fcdaee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-default.Button__DefaultButton-sc-1jltwde-0.Button__IconButton-sc-1jltwde-2.jTffPG.imHUOe.ant-tooltip-open.bottom-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76a865b7-d85f-4de8-bad1-7ce3dad96879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bc753ff-91cd-4f73-b78a-29fc88491b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default Button__DefaultButton-sc-1jltwde-0 Button__IconButton-sc-1jltwde-2 jTffPG imHUOe ant-tooltip-open bottom-button</value>
      <webElementGuid>b166be90-6d3c-4ee7-8afc-7227d689121b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;reactRoot&quot;]/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content content&quot;]/div[@class=&quot;indexstyled__PageContentWrapper-sc-u7rmmc-1 kTboPR page-container-wrapper&quot;]/div[@class=&quot;indexstyled__PageContentInnerWrapper-sc-u7rmmc-5 bpiSfM&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col location-card ant-col-lg-12&quot;]/div[@class=&quot;indexstyled__DivLocationCardWrapper-sc-kkj6g9-0 jFhrXa&quot;]/div[@class=&quot;ant-space ant-space-horizontal ant-space-align-center Space__SpaceWrapper-sc-mc78sm-0 dDQMXX indexstyled__LocationCardFooterWrapper-sc-kkj6g9-6 cvcUAM location-card-footer-wrapper&quot;]/div[@class=&quot;ant-space-item&quot;]/button[@class=&quot;ant-btn ant-btn-default Button__DefaultButton-sc-1jltwde-0 Button__IconButton-sc-1jltwde-2 jTffPG imHUOe ant-tooltip-open bottom-button&quot;]</value>
      <webElementGuid>9dca20e9-189d-46e6-b7e5-485d0e81118c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>e16e4a0f-d9d9-408c-8b1b-ba89dacbe146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/main/div/div[2]/div/div[2]/div/div[3]/div[2]/button</value>
      <webElementGuid>83b9e645-0f9c-49fa-92cb-d95269390786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total energy'])[2]/following::button[2]</value>
      <webElementGuid>e5534dd5-9be3-4c8b-ab39-bd32ecedf8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of load cap'])[2]/following::button[2]</value>
      <webElementGuid>93a2bad4-919b-44a5-a56f-c2f600d9b500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lyam 50 - Jovan Dickinson 2'])[1]/preceding::button[4]</value>
      <webElementGuid>14bd7cce-dfff-4932-9507-4fb4da242a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lite'])[1]/preceding::button[4]</value>
      <webElementGuid>2c119e4a-5a9d-4d14-8c75-44ac1fd18a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[2]/button</value>
      <webElementGuid>5c75c99a-ab32-45fb-a8f1-01df80c626d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>86db277c-5a45-49a0-90c2-873b4458c897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
