<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Monday</name>
   <tag></tag>
   <elementGuidId>d130c4f8-5fa2-422a-aa1a-48195820e7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='LocationSettingsForm']/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/table/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b6715552-a4c5-487c-ae46-95b365fa8c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>57431a98-1b5a-480d-b0d8-86cd1b32c2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monday</value>
      <webElementGuid>ee757e53-f1b1-45cb-b81f-a226ad3f02d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationSettingsForm&quot;)/div[@class=&quot;ant-space ant-space-vertical Space__SpaceWrapper-sc-mc78sm-0 dDQMXX&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24 ant-col-lg-8&quot;]/div[@class=&quot;ant-space ant-space-vertical Space__SpaceWrapper-sc-mc78sm-0 dDQMXX&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;ant-form-item ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;indexstyled__DivLocationCardWrapper-sc-kkj6g9-0 jFhrXa&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[1]/table[@class=&quot;PublicAvailabilityFeature__ScheduleTableWrapper-sc-193bap7-0 gqnOlV&quot;]/tr[1]/td[1]</value>
      <webElementGuid>3d857ba5-693d-4c73-93ca-4c241c7a8b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LocationSettingsForm']/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/table/tr/td</value>
      <webElementGuid>84181c32-5935-4d7c-93b7-82fb46cd9ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC AVAILABILITY'])[1]/following::td[1]</value>
      <webElementGuid>83d75623-a4f0-41c4-a918-1eca386f7125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ON'])[2]/following::td[1]</value>
      <webElementGuid>700d98d8-855e-4459-ad77-aa08b69db04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All-day'])[1]/preceding::td[1]</value>
      <webElementGuid>1ec86865-4ccf-40b2-a731-901e15939815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT HOURS'])[1]/preceding::td[2]</value>
      <webElementGuid>1fc4748f-f5b3-41bf-af47-6ee930173b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monday']/parent::*</value>
      <webElementGuid>6eb378a9-1261-402e-8920-e7021188f849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>72d9bc10-09ae-4259-92db-89feadfe8386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Monday' or . = 'Monday')]</value>
      <webElementGuid>9485e14b-ecc2-4e49-8135-89db6f8ca24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
