<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Tuesday</name>
   <tag></tag>
   <elementGuidId>4afb0cbd-7947-470c-b75d-58f0b7dcebf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='LocationSettingsForm']/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/table/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>731b0b43-fcd9-4b5c-983d-93e0fb628371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>4967c7f3-ac4c-47a2-8636-42bf290fd762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tuesday</value>
      <webElementGuid>fbca7ba2-c7dc-4713-a91a-987bd33958b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationSettingsForm&quot;)/div[@class=&quot;ant-space ant-space-vertical Space__SpaceWrapper-sc-mc78sm-0 dDQMXX&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24 ant-col-lg-8&quot;]/div[@class=&quot;ant-space ant-space-vertical Space__SpaceWrapper-sc-mc78sm-0 dDQMXX&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;ant-form-item ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;indexstyled__DivLocationCardWrapper-sc-kkj6g9-0 jFhrXa&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[1]/table[@class=&quot;PublicAvailabilityFeature__ScheduleTableWrapper-sc-193bap7-0 gqnOlV&quot;]/tr[2]/td[1]</value>
      <webElementGuid>8ee2f5d9-6503-4f9c-b7b5-3ba340bf2507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LocationSettingsForm']/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/table/tr[2]/td</value>
      <webElementGuid>1461b0df-f576-447f-9433-47fd559ad14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All-day'])[1]/following::td[1]</value>
      <webElementGuid>8493ea48-2bbe-44d6-8578-51ccb695d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monday'])[1]/following::td[2]</value>
      <webElementGuid>2c2d368f-14cc-4f00-b41a-9b1671a05b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All-day'])[2]/preceding::td[1]</value>
      <webElementGuid>c959cfc4-e6c5-48f8-9af8-d212898ab677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT HOURS'])[1]/preceding::td[2]</value>
      <webElementGuid>05626f0e-34ed-4bba-8e89-9f276fd68792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tuesday']/parent::*</value>
      <webElementGuid>380ad32d-fe98-4d4c-8333-fda91eaaaa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>fc17294d-7ac4-4cf0-add0-ffd61611d8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Tuesday' or . = 'Tuesday')]</value>
      <webElementGuid>879a66c9-2f2a-4a20-8313-03de929b2a1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
